enum ENumberArrayType {
  COLOUR = "colour",
  PRESERVATIVE = "preservative",
  ANTIOXIDANT = "antioxidant",
  SWEETENER = "sweetener",
  EMULSIFIER = "emulsifier",
  OTHER = "other",
}

type ENumberArrayItem = {
  code: string;
  type: ENumberArrayType;
  name: string;
  licensedInEU: boolean;
};

export const E_NUMBERS: ENumberArrayItem[] = [
  /* Colours */
  {
    code: "E100",
    type: ENumberArrayType.COLOUR,
    name: "Curcumin",
    licensedInEU: true,
  },
  {
    code: "E101a",
    type: ENumberArrayType.COLOUR,
    name: "Riboflavin-5-phosphate",
    licensedInEU: true,
  },
  {
    code: "E102",
    type: ENumberArrayType.COLOUR,
    name: "Tartrazine",
    licensedInEU: true,
  },
  {
    code: "E103",
    type: ENumberArrayType.COLOUR,
    name: "Alkanet, Alkannin",
    licensedInEU: false,
  },
  {
    code: "E104",
    type: ENumberArrayType.COLOUR,
    name: "Quinoline yellow",
    licensedInEU: true,
  },
  {
    code: "E105",
    type: ENumberArrayType.COLOUR,
    name: "Fast yellow AB, Yellow 2G",
    licensedInEU: false,
  },
  {
    code: "E106",
    type: ENumberArrayType.COLOUR,
    name: "Riboflavin-5-natriumphosphate",
    licensedInEU: false,
  },
  {
    code: "E107",
    type: ENumberArrayType.COLOUR,
    name: "Yellow 2G",
    licensedInEU: false,
  },
  {
    code: "E110",
    type: ENumberArrayType.COLOUR,
    name: "Sunset yellow FCF",
    licensedInEU: true,
  },
  {
    code: "E111",
    type: ENumberArrayType.COLOUR,
    name: "Orange GGN",
    licensedInEU: false,
  },
  {
    code: "E121",
    type: ENumberArrayType.COLOUR,
    name: "Citrus Red 2",
    licensedInEU: false,
  },
  {
    code: "E122",
    type: ENumberArrayType.COLOUR,
    name: "Carmoisine, Azorubine",
    licensedInEU: true,
  },
  {
    code: "E123",
    type: ENumberArrayType.COLOUR,
    name: "Amaranth",
    licensedInEU: true,
  },
  {
    code: "E124",
    type: ENumberArrayType.COLOUR,
    name: "Ponceau 4R, Cochineal Red A",
    licensedInEU: true,
  },
  {
    code: "E125",
    type: ENumberArrayType.COLOUR,
    name: "Ponceau SX, Scarlet GN",
    licensedInEU: false,
  },
  {
    code: "E126",
    type: ENumberArrayType.COLOUR,
    name: "Pyranine",
    licensedInEU: false,
  },
  {
    code: "E127",
    type: ENumberArrayType.COLOUR,
    name: "Erythrosine, Red No. 3",
    licensedInEU: false,
  },
  {
    code: "E128",
    type: ENumberArrayType.COLOUR,
    name: "Red 2G",
    licensedInEU: false,
  },
  {
    code: "E129",
    type: ENumberArrayType.COLOUR,
    name: "Allura Red AC, Red No. 40",
    licensedInEU: true,
  },
  {
    code: "E130",
    type: ENumberArrayType.COLOUR,
    name: "Indigo carmine, Indigotine",
    licensedInEU: false,
  },
  {
    code: "E131",
    type: ENumberArrayType.COLOUR,
    name: "Patent Blue V",
    licensedInEU: true,
  },
  {
    code: "E132",
    type: ENumberArrayType.COLOUR,
    name: "Indigo Carmine (Aluminium Lake)",
    licensedInEU: true,
  },
  {
    code: "E133",
    type: ENumberArrayType.COLOUR,
    name: "Brilliant Blue FCF, Blue No. 1",
    licensedInEU: true,
  },
  {
    code: "E140",
    type: ENumberArrayType.COLOUR,
    name: "Chlorophylls and Chlorophyllins",
    licensedInEU: true,
  },
  {
    code: "E141",
    type: ENumberArrayType.COLOUR,
    name: "Copper complexes of chlorophyllins",
    licensedInEU: true,
  },
  {
    code: "E142",
    type: ENumberArrayType.COLOUR,
    name: "Green S",
    licensedInEU: true,
  },
  {
    code: "E143",
    type: ENumberArrayType.COLOUR,
    name: "Fast Green FCF",
    licensedInEU: false,
  },
  {
    code: "E150a",
    type: ENumberArrayType.COLOUR,
    name: "Plain caramel",
    licensedInEU: true,
  },
  {
    code: "E150b",
    type: ENumberArrayType.COLOUR,
    name: "Caustic sulphite caramel",
    licensedInEU: true,
  },
  {
    code: "E150c",
    type: ENumberArrayType.COLOUR,
    name: "Ammonia caramel",
    licensedInEU: true,
  },
  {
    code: "E150d",
    type: ENumberArrayType.COLOUR,
    name: "Sulphite ammonia caramel",
    licensedInEU: true,
  },
  {
    code: "E151",
    type: ENumberArrayType.COLOUR,
    name: "Brilliant Black BN, Black PN",
    licensedInEU: true,
  },
  {
    code: "E152",
    type: ENumberArrayType.COLOUR,
    name: "Black 7984, Food Black 1",
    licensedInEU: false,
  },
  {
    code: "E153",
    type: ENumberArrayType.COLOUR,
    name: "Vegetable carbon",
    licensedInEU: true,
  },
  {
    code: "E154",
    type: ENumberArrayType.COLOUR,
    name: "Brown FK",
    licensedInEU: false,
  },
  {
    code: "E155",
    type: ENumberArrayType.COLOUR,
    name: "Brown HT",
    licensedInEU: true,
  },
  {
    code: "E160a",
    type: ENumberArrayType.COLOUR,
    name: "Alpha-carotene",
    licensedInEU: true,
  },
  {
    code: "E160b",
    type: ENumberArrayType.COLOUR,
    name: "Annatto, Bixin, Norbixin",
    licensedInEU: true,
  },
  {
    code: "E160c",
    type: ENumberArrayType.COLOUR,
    name: "Paprika extract, Capsanthin, Capsorubin",
    licensedInEU: true,
  },
  {
    code: "E160d",
    type: ENumberArrayType.COLOUR,
    name: "Lycopene",
    licensedInEU: true,
  },
  {
    code: "E160e",
    type: ENumberArrayType.COLOUR,
    name: "Beta-apo-8'-carotenal (C30)",
    licensedInEU: true,
  },
  {
    code: "E160f",
    type: ENumberArrayType.COLOUR,
    name: "Ethyl ester of beta-apo-8'-carotenoic acid",
    licensedInEU: false,
  },
  {
    code: "E161a",
    type: ENumberArrayType.COLOUR,
    name: "Flavoxanthin",
    licensedInEU: false,
  },
  {
    code: "E161b",
    type: ENumberArrayType.COLOUR,
    name: "Lutein",
    licensedInEU: true,
  },
  {
    code: "E161c",
    type: ENumberArrayType.COLOUR,
    name: "Cryptoxanthin",
    licensedInEU: false,
  },
  {
    code: "E161d",
    type: ENumberArrayType.COLOUR,
    name: "Rubixanthin",
    licensedInEU: false,
  },
  {
    code: "E161e",
    type: ENumberArrayType.COLOUR,
    name: "Violaxanthin",
    licensedInEU: false,
  },
  {
    code: "E161f",
    type: ENumberArrayType.COLOUR,
    name: "Rhodoxanthin",
    licensedInEU: false,
  },
  {
    code: "E161g",
    type: ENumberArrayType.COLOUR,
    name: "Canthaxanthin",
    licensedInEU: true,
  },
  {
    code: "E161h",
    type: ENumberArrayType.COLOUR,
    name: "Zeaxanthin",
    licensedInEU: false,
  },
  {
    code: "E162",
    type: ENumberArrayType.COLOUR,
    name: "Beetroot Red, Betanin",
    licensedInEU: true,
  },
  {
    code: "E163",
    type: ENumberArrayType.COLOUR,
    name: "Anthocyanins",
    licensedInEU: true,
  },
  {
    code: "E170",
    type: ENumberArrayType.COLOUR,
    name: "Calcium carbonate",
    licensedInEU: true,
  },
  {
    code: "E171",
    type: ENumberArrayType.COLOUR,
    name: "Titanium dioxide",
    licensedInEU: false,
  },
  {
    code: "E172",
    type: ENumberArrayType.COLOUR,
    name: "Iron oxides and hydroxides",
    licensedInEU: true,
  },
  {
    code: "E173",
    type: ENumberArrayType.COLOUR,
    name: "Aluminium",
    licensedInEU: true,
  },
  {
    code: "E174",
    type: ENumberArrayType.COLOUR,
    name: "Silver",
    licensedInEU: true,
  },
  {
    code: "E175",
    type: ENumberArrayType.COLOUR,
    name: "Gold",
    licensedInEU: true,
  },
  {
    code: "E180",
    type: ENumberArrayType.COLOUR,
    name: "Litholrubine BK",
    licensedInEU: false,
  },
  {
    code: "E181",
    type: ENumberArrayType.COLOUR,
    name: "Cocoas brown",
    licensedInEU: false,
  },
  /* Preservatives */
  {
    code: "E200",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sorbic acid",
    licensedInEU: true,
  },
  {
    code: "E201",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium sorbate",
    licensedInEU: false,
  },
  {
    code: "E202",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium sorbate",
    licensedInEU: true,
  },
  {
    code: "E203",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium sorbate",
    licensedInEU: false,
  },
  {
    code: "E210",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Benzoic acid",
    licensedInEU: true,
  },
  {
    code: "E211",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium benzoate",
    licensedInEU: true,
  },
  {
    code: "E212",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium benzoate",
    licensedInEU: true,
  },
  {
    code: "E213",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium benzoate",
    licensedInEU: true,
  },
  {
    code: "E214",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Ethyl p-hydroxybenzoate (Ethylparaben)",
    licensedInEU: true,
  },
  {
    code: "E215",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium ethyl p-hydroxybenzoate (Sodium ethylparaben)",
    licensedInEU: false,
  },
  {
    code: "E216",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Propyl p-hydroxybenzoate (Propylparaben)",
    licensedInEU: false,
  },
  {
    code: "E217",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium propyl p-hydroxybenzoate (Sodium propylparaben)",
    licensedInEU: false,
  },
  {
    code: "E218",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Methyl p-hydroxybenzoate (Methylparaben)",
    licensedInEU: true,
  },
  {
    code: "E219",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium methyl p-hydroxybenzoate (Sodium methylparaben)",
    licensedInEU: false,
  },
  {
    code: "E220",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sulphur dioxide",
    licensedInEU: true,
  },
  {
    code: "E221",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium sulphite",
    licensedInEU: true,
  },
  {
    code: "E222",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium bisulphite",
    licensedInEU: true,
  },
  {
    code: "E223",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium metabisulphite",
    licensedInEU: true,
  },
  {
    code: "E224",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium metabisulphite",
    licensedInEU: true,
  },
  {
    code: "E225",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium sulphite",
    licensedInEU: false,
  },
  {
    code: "E226",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium sulphite",
    licensedInEU: true,
  },
  {
    code: "E227",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium hydrogen sulphite",
    licensedInEU: true,
  },
  {
    code: "E228",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium hydrogen sulphite",
    licensedInEU: true,
  },
  {
    code: "E230",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Biphenyl",
    licensedInEU: false,
  },
  {
    code: "E231",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Orthophenylphenol",
    licensedInEU: false,
  },
  {
    code: "E232",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium orthophenylphenol",
    licensedInEU: false,
  },
  {
    code: "E233",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Thiabendazole",
    licensedInEU: false,
  },
  {
    code: "E234",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Nisin",
    licensedInEU: true,
  },
  {
    code: "E235",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Natamycin (Pimaricin)",
    licensedInEU: true,
  },
  {
    code: "E236",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Formic acid",
    licensedInEU: false,
  },
  {
    code: "E237",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium formate",
    licensedInEU: false,
  },
  {
    code: "E238",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium formate",
    licensedInEU: false,
  },
  {
    code: "E239",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Hexamethylene tetramine",
    licensedInEU: true,
  },
  {
    code: "E240",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Formaldehyde",
    licensedInEU: false,
  },
  {
    code: "E242",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Dimethyl dicarbonate",
    licensedInEU: true,
  },
  {
    code: "E249",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium nitrite",
    licensedInEU: true,
  },
  {
    code: "E250",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium nitrite",
    licensedInEU: true,
  },
  {
    code: "E251",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium nitrate",
    licensedInEU: true,
  },
  {
    code: "E260",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Acetic acid",
    licensedInEU: true,
  },
  {
    code: "E261",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium acetate",
    licensedInEU: true,
  },
  {
    code: "E262",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium acetate",
    licensedInEU: true,
  },
  {
    code: "E263",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium acetate",
    licensedInEU: true,
  },
  {
    code: "E264",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium acetate",
    licensedInEU: false,
  },
  {
    code: "E265",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium propionate",
    licensedInEU: false,
  },
  {
    code: "E266",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium propionate",
    licensedInEU: false,
  },
  {
    code: "E280",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Propionic acid",
    licensedInEU: true,
  },
  {
    code: "E281",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium propionate",
    licensedInEU: true,
  },
  {
    code: "E282",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium propionate",
    licensedInEU: true,
  },
  {
    code: "E283",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium propionate",
    licensedInEU: false,
  },
  {
    code: "E284",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Boric acid",
    licensedInEU: false,
  },
  {
    code: "E285",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Borax",
    licensedInEU: false,
  },
  {
    code: "E290",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Carbon dioxide",
    licensedInEU: true,
  },
  {
    code: "E296",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Malic acid",
    licensedInEU: true,
  },
  {
    code: "E297",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Fumaric acid",
    licensedInEU: true,
  },
  /* Antioxidants */
  {
    code: "E300",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ascorbic acid (Vitamin C)",
    licensedInEU: true,
  },
  {
    code: "E301",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium ascorbate",
    licensedInEU: true,
  },
  {
    code: "E302",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium ascorbate",
    licensedInEU: true,
  },
  {
    code: "E303",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium ascorbate",
    licensedInEU: false,
  },
  {
    code: "E304",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Fatty acid esters of ascorbic acid",
    licensedInEU: true,
  },
  {
    code: "E306",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Tocopherols (Vitamin E)",
    licensedInEU: true,
  },
  {
    code: "E307",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Alpha-tocopherol",
    licensedInEU: true,
  },
  {
    code: "E308",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Gamma-tocopherol",
    licensedInEU: true,
  },
  {
    code: "E309",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Delta-tocopherol",
    licensedInEU: true,
  },
  {
    code: "E310",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Propyl gallate",
    licensedInEU: true,
  },
  {
    code: "E311",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Octyl gallate",
    licensedInEU: false,
  },
  {
    code: "E312",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Dodecyl gallate",
    licensedInEU: false,
  },
  {
    code: "E315",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Erythorbic acid (Isoascorbic acid)",
    licensedInEU: true,
  },
  {
    code: "E316",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium erythorbate",
    licensedInEU: true,
  },
  {
    code: "E317",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium erythorbate",
    licensedInEU: false,
  },
  {
    code: "E318",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Thiourea",
    licensedInEU: false,
  },
  {
    code: "E319",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Tertiary butylhydroquinone (TBHQ)",
    licensedInEU: true,
  },
  {
    code: "E320",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Butylated hydroxyanisole (BHA)",
    licensedInEU: true,
  },
  {
    code: "E321",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Butylated hydroxytoluene (BHT)",
    licensedInEU: true,
  },
  {
    code: "E329",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Magnesium lactate",
    licensedInEU: false,
  },
  {
    code: "E330",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Citric acid",
    licensedInEU: true,
  },
  {
    code: "E331",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium citrates",
    licensedInEU: true,
  },
  {
    code: "E332",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium citrates",
    licensedInEU: true,
  },
  {
    code: "E333",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium citrates",
    licensedInEU: true,
  },
  {
    code: "E334",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Tartaric acid",
    licensedInEU: true,
  },
  {
    code: "E335",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium tartrates",
    licensedInEU: true,
  },
  {
    code: "E336",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium tartrates",
    licensedInEU: true,
  },
  {
    code: "E337",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium sodium tartrate",
    licensedInEU: false,
  },
  {
    code: "E338",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Phosphoric acid",
    licensedInEU: true,
  },
  {
    code: "E339",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium phosphates",
    licensedInEU: true,
  },
  {
    code: "E340",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium phosphates",
    licensedInEU: true,
  },
  {
    code: "E341",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium phosphates",
    licensedInEU: true,
  },
  {
    code: "E343",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Magnesium phosphates",
    licensedInEU: true,
  },
  {
    code: "E350",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Malates",
    licensedInEU: true,
  },
  {
    code: "E351",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium malate",
    licensedInEU: true,
  },
  {
    code: "E352",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium malate",
    licensedInEU: true,
  },
  {
    code: "E353",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Metatartaric acid",
    licensedInEU: true,
  },
  {
    code: "E354",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium tartrate",
    licensedInEU: true,
  },
  {
    code: "E355",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Adipic acid",
    licensedInEU: false,
  },
  {
    code: "E356",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium adipate",
    licensedInEU: false,
  },
  {
    code: "E357",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium adipate",
    licensedInEU: false,
  },
  {
    code: "E363",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Succinic acid",
    licensedInEU: true,
  },
  {
    code: "E365",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium fumarate",
    licensedInEU: false,
  },
  {
    code: "E366",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium fumarate",
    licensedInEU: false,
  },
  {
    code: "E367",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium fumarate",
    licensedInEU: false,
  },
  {
    code: "E370",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "1,4-Heptonolacton",
    licensedInEU: false,
  },
  {
    code: "E375",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Nicotinamide",
    licensedInEU: false,
  },
  {
    code: "E380",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Triammonium citrate",
    licensedInEU: true,
  },
  {
    code: "E381",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ammonium citrate",
    licensedInEU: false,
  },
  {
    code: "E385",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ethylenediaminetetraacetic acid",
    licensedInEU: true,
  },
  /* Emulsifiers */
  {
    code: "E400",
    type: ENumberArrayType.EMULSIFIER,
    name: "Alginic acid",
    licensedInEU: true,
  },
  {
    code: "E401",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sodium alginate",
    licensedInEU: true,
  },
  {
    code: "E402",
    type: ENumberArrayType.EMULSIFIER,
    name: "Potassium alginate",
    licensedInEU: true,
  },
  {
    code: "E403",
    type: ENumberArrayType.EMULSIFIER,
    name: "Ammonium alginate",
    licensedInEU: false,
  },
  {
    code: "E404",
    type: ENumberArrayType.EMULSIFIER,
    name: "Calcium alginate",
    licensedInEU: true,
  },
  {
    code: "E405",
    type: ENumberArrayType.EMULSIFIER,
    name: "Propylene glycol alginate",
    licensedInEU: true,
  },
  {
    code: "E406",
    type: ENumberArrayType.EMULSIFIER,
    name: "Agar",
    licensedInEU: true,
  },
  {
    code: "E407",
    type: ENumberArrayType.EMULSIFIER,
    name: "Carrageenan",
    licensedInEU: true,
  },
  {
    code: "E407a",
    type: ENumberArrayType.EMULSIFIER,
    name: "Processed eucheuma seaweed",
    licensedInEU: true,
  },
  {
    code: "E410",
    type: ENumberArrayType.EMULSIFIER,
    name: "Locust bean gum, Carob gum",
    licensedInEU: true,
  },
  {
    code: "E412",
    type: ENumberArrayType.EMULSIFIER,
    name: "Guar gum",
    licensedInEU: true,
  },
  {
    code: "E413",
    type: ENumberArrayType.EMULSIFIER,
    name: "Tragacanth",
    licensedInEU: true,
  },
  {
    code: "E414",
    type: ENumberArrayType.EMULSIFIER,
    name: "Acacia gum, Gum arabic",
    licensedInEU: true,
  },
  {
    code: "E415",
    type: ENumberArrayType.EMULSIFIER,
    name: "Xanthan gum",
    licensedInEU: true,
  },
  {
    code: "E416",
    type: ENumberArrayType.EMULSIFIER,
    name: "Karaya gum",
    licensedInEU: true,
  },
  {
    code: "E417",
    type: ENumberArrayType.EMULSIFIER,
    name: "Tara gum",
    licensedInEU: false,
  },
  {
    code: "E418",
    type: ENumberArrayType.EMULSIFIER,
    name: "Gellan gum",
    licensedInEU: true,
  },
  {
    code: "E420",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sorbitol",
    licensedInEU: true,
  },
  {
    code: "E421",
    type: ENumberArrayType.EMULSIFIER,
    name: "Mannitol",
    licensedInEU: true,
  },
  {
    code: "E425",
    type: ENumberArrayType.EMULSIFIER,
    name: "Konjac",
    licensedInEU: true,
  },
  {
    code: "E440",
    type: ENumberArrayType.EMULSIFIER,
    name: "Pectin",
    licensedInEU: true,
  },
  {
    code: "E444",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sucrose acetate isobutyrate",
    licensedInEU: true,
  },
  {
    code: "E450",
    type: ENumberArrayType.EMULSIFIER,
    name: "Diphosphates",
    licensedInEU: true,
  },
  {
    code: "E451",
    type: ENumberArrayType.EMULSIFIER,
    name: "Triphosphates",
    licensedInEU: true,
  },
  {
    code: "E452",
    type: ENumberArrayType.EMULSIFIER,
    name: "Polyphosphates",
    licensedInEU: true,
  },
  {
    code: "E459",
    type: ENumberArrayType.EMULSIFIER,
    name: "Cyclodextrin",
    licensedInEU: false,
  },
  {
    code: "E460",
    type: ENumberArrayType.EMULSIFIER,
    name: "Cellulose",
    licensedInEU: true,
  },
  {
    code: "E461",
    type: ENumberArrayType.EMULSIFIER,
    name: "Methyl cellulose",
    licensedInEU: true,
  },
  {
    code: "E462",
    type: ENumberArrayType.EMULSIFIER,
    name: "Ethyl cellulose",
    licensedInEU: false,
  },
  {
    code: "E463",
    type: ENumberArrayType.EMULSIFIER,
    name: "Hydroxypropyl cellulose",
    licensedInEU: false,
  },
  {
    code: "E464",
    type: ENumberArrayType.EMULSIFIER,
    name: "Hydroxypropyl methyl cellulose",
    licensedInEU: false,
  },
  {
    code: "E465",
    type: ENumberArrayType.EMULSIFIER,
    name: "Ethyl methyl cellulose",
    licensedInEU: false,
  },
  {
    code: "E466",
    type: ENumberArrayType.EMULSIFIER,
    name: "Carboxymethyl cellulose",
    licensedInEU: true,
  },
  {
    code: "E468",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sodium croscarmellose",
    licensedInEU: false,
  },
  {
    code: "E469",
    type: ENumberArrayType.EMULSIFIER,
    name: "Enzymatically hydrolysed sodium carboxymethylcellulose",
    licensedInEU: false,
  },
  /* Other */
  {
    code: "E500",
    type: ENumberArrayType.OTHER,
    name: "Sodium carbonates",
    licensedInEU: true,
  },
  {
    code: "E501",
    type: ENumberArrayType.OTHER,
    name: "Potassium carbonates",
    licensedInEU: true,
  },
  {
    code: "E503",
    type: ENumberArrayType.OTHER,
    name: "Magnesium carbonates",
    licensedInEU: false,
  },
  {
    code: "E504",
    type: ENumberArrayType.OTHER,
    name: "Magnesium hydrogen carbonate",
    licensedInEU: false,
  },
  {
    code: "E507",
    type: ENumberArrayType.OTHER,
    name: "Hydrochloric acid",
    licensedInEU: true,
  },
  {
    code: "E508",
    type: ENumberArrayType.OTHER,
    name: "Potassium chloride",
    licensedInEU: true,
  },
  {
    code: "E509",
    type: ENumberArrayType.OTHER,
    name: "Calcium chloride",
    licensedInEU: true,
  },
  {
    code: "E510",
    type: ENumberArrayType.OTHER,
    name: "Ammonium chloride",
    licensedInEU: false,
  },
  {
    code: "E511",
    type: ENumberArrayType.OTHER,
    name: "Magnesium chloride",
    licensedInEU: false,
  },
  {
    code: "E512",
    type: ENumberArrayType.OTHER,
    name: "Stannous chloride",
    licensedInEU: false,
  },
  {
    code: "E513",
    type: ENumberArrayType.OTHER,
    name: "Sulphuric acid",
    licensedInEU: true,
  },
  {
    code: "E517",
    type: ENumberArrayType.OTHER,
    name: "Ammonium sulphate",
    licensedInEU: false,
  },
  {
    code: "E518",
    type: ENumberArrayType.OTHER,
    name: "Magnesium sulphate",
    licensedInEU: true,
  },
  {
    code: "E519",
    type: ENumberArrayType.OTHER,
    name: "Calcium sulphate",
    licensedInEU: true,
  },
  {
    code: "E520",
    type: ENumberArrayType.OTHER,
    name: "Aluminium sulphates",
    licensedInEU: false,
  },
  {
    code: "E521",
    type: ENumberArrayType.OTHER,
    name: "Aluminium sodium sulphates",
    licensedInEU: false,
  },
  {
    code: "E522",
    type: ENumberArrayType.OTHER,
    name: "Aluminium potassium sulphates",
    licensedInEU: false,
  },
  {
    code: "E523",
    type: ENumberArrayType.OTHER,
    name: "Aluminium ammonium sulphates",
    licensedInEU: false,
  },
  {
    code: "E524",
    type: ENumberArrayType.OTHER,
    name: "Sodium hydroxide",
    licensedInEU: true,
  },
  {
    code: "E525",
    type: ENumberArrayType.OTHER,
    name: "Potassium hydroxide",
    licensedInEU: true,
  },
  {
    code: "E526",
    type: ENumberArrayType.OTHER,
    name: "Calcium hydroxide",
    licensedInEU: true,
  },
  {
    code: "E527",
    type: ENumberArrayType.OTHER,
    name: "Ammonium hydroxide",
    licensedInEU: false,
  },
  {
    code: "E528",
    type: ENumberArrayType.OTHER,
    name: "Magnesium hydroxide",
    licensedInEU: false,
  },
  {
    code: "E529",
    type: ENumberArrayType.OTHER,
    name: "Lithium hydroxide",
    licensedInEU: false,
  },
  {
    code: "E530",
    type: ENumberArrayType.OTHER,
    name: "Magnesium oxide",
    licensedInEU: true,
  },
  {
    code: "E535",
    type: ENumberArrayType.OTHER,
    name: "Sodium ferrocyanide",
    licensedInEU: true,
  },
  {
    code: "E536",
    type: ENumberArrayType.OTHER,
    name: "Potassium ferrocyanide",
    licensedInEU: true,
  },
  {
    code: "E538",
    type: ENumberArrayType.OTHER,
    name: "Calcium ferrocyanide",
    licensedInEU: true,
  },
];
