// Auto-generated from Wikipedia E-number tables + curated overrides
// See: https://en.wikipedia.org/wiki/E_number
// EU ban for E171 per Commission (2022).

export enum ENumberArrayType {
  COLOUR = "colour",
  PRESERVATIVE = "preservative",
  ANTIOXIDANT = "antioxidant",
  SWEETENER = "sweetener",
  EMULSIFIER = "emulsifier",
  OTHER = "other",
}

export type ENumberArrayItem = {
  code: string;
  type: ENumberArrayType;
  name: string;
  licensedInEU: boolean;
  vegan: boolean;
};

export const veganENumbersFull: ENumberArrayItem[] = [
  {
    code: "E100",
    type: ENumberArrayType.COLOUR,
    name: "Curcumin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E101a",
    type: ENumberArrayType.COLOUR,
    name: "Riboflavin-5'-phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E102",
    type: ENumberArrayType.COLOUR,
    name: "Tartrazine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E103",
    type: ENumberArrayType.COLOUR,
    name: "Alkannin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E104",
    type: ENumberArrayType.COLOUR,
    name: "Quinoline Yellow WS",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E105",
    type: ENumberArrayType.COLOUR,
    name: "Fast Yellow AB",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E106",
    type: ENumberArrayType.COLOUR,
    name: "Riboflavin-5-Sodium Phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E107",
    type: ENumberArrayType.COLOUR,
    name: "Yellow 2G",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E110",
    type: ENumberArrayType.COLOUR,
    name: "Sunset Yellow FCF",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E111",
    type: ENumberArrayType.COLOUR,
    name: "Orange GGN",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E121",
    type: ENumberArrayType.COLOUR,
    name: "Citrus Red 2",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E122",
    type: ENumberArrayType.COLOUR,
    name: "Carmoisine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E123",
    type: ENumberArrayType.COLOUR,
    name: "Amaranth",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E124",
    type: ENumberArrayType.COLOUR,
    name: "Ponceau 4R",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E125",
    type: ENumberArrayType.COLOUR,
    name: "Ponceau SX",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E126",
    type: ENumberArrayType.COLOUR,
    name: "Ponceau 6R",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E127",
    type: ENumberArrayType.COLOUR,
    name: "Erythrosine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E128",
    type: ENumberArrayType.COLOUR,
    name: "Red 2G",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E129",
    type: ENumberArrayType.COLOUR,
    name: "Allura Red AC",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E130",
    type: ENumberArrayType.COLOUR,
    name: "Indanthrene Blue RS",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E131",
    type: ENumberArrayType.COLOUR,
    name: "Patent Blue V",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E132",
    type: ENumberArrayType.COLOUR,
    name: "Indigo Carmine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E133",
    type: ENumberArrayType.COLOUR,
    name: "Brilliant Blue FCF",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E140",
    type: ENumberArrayType.COLOUR,
    name: "Chlorophylls and Chlorophyllins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E141",
    type: ENumberArrayType.COLOUR,
    name: "Copper Complexes of Chlorophylls and Chlorophyllins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E142",
    type: ENumberArrayType.COLOUR,
    name: "Green S",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E143",
    type: ENumberArrayType.COLOUR,
    name: "Fast Green FCF",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E150a",
    type: ENumberArrayType.COLOUR,
    name: "Plain caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E150b",
    type: ENumberArrayType.COLOUR,
    name: "Caustic sulphite caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E150c",
    type: ENumberArrayType.COLOUR,
    name: "Ammonia caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E150d",
    type: ENumberArrayType.COLOUR,
    name: "Sulfite ammonia caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E151",
    type: ENumberArrayType.COLOUR,
    name: "Black PN",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E152",
    type: ENumberArrayType.COLOUR,
    name: "Carbon Black",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E154",
    type: ENumberArrayType.COLOUR,
    name: "Brown FK",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E155",
    type: ENumberArrayType.COLOUR,
    name: "Brown HT",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E160a",
    type: ENumberArrayType.COLOUR,
    name: "Alpha-carotene/Beta-carotene (mixed carotenoids)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E160b",
    type: ENumberArrayType.COLOUR,
    name: "Annatto, bixin, norbixin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E160c",
    type: ENumberArrayType.COLOUR,
    name: "Paprika extract, capsanthin, capsorubin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E160d",
    type: ENumberArrayType.COLOUR,
    name: "Lycopene",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E160e",
    type: ENumberArrayType.COLOUR,
    name: "Beta-apo-8'-carotenal",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E160f",
    type: ENumberArrayType.COLOUR,
    name: "Ethyl ester of beta-apo-8'-carotenic acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E161a",
    type: ENumberArrayType.COLOUR,
    name: "Flavoxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E161b",
    type: ENumberArrayType.COLOUR,
    name: "Lutein",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E161c",
    type: ENumberArrayType.COLOUR,
    name: "Cryptoxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E161d",
    type: ENumberArrayType.COLOUR,
    name: "Rubixanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E161e",
    type: ENumberArrayType.COLOUR,
    name: "Violaxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E161f",
    type: ENumberArrayType.COLOUR,
    name: "Rhodoxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E162",
    type: ENumberArrayType.COLOUR,
    name: "Curcumin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E163",
    type: ENumberArrayType.COLOUR,
    name: "Riboflavin-5'-Phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E170",
    type: ENumberArrayType.COLOUR,
    name: "Tartrazine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E171",
    type: ENumberArrayType.COLOUR,
    name: "Alkannin",
    licensedInEU: false,
    vegan: true,
  },
  {
    code: "E172",
    type: ENumberArrayType.COLOUR,
    name: "Quinoline Yellow WS",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E173",
    type: ENumberArrayType.COLOUR,
    name: "Fast Yellow AB",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E174",
    type: ENumberArrayType.COLOUR,
    name: "Riboflavin-5-Sodium Phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E175",
    type: ENumberArrayType.COLOUR,
    name: "Yellow 2G",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E180",
    type: ENumberArrayType.COLOUR,
    name: "Sunset Yellow FCF",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E181",
    type: ENumberArrayType.COLOUR,
    name: "Orange GGN",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E200",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Citrus Red 2",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E201",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Carmoisine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E202",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Amaranth",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E203",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Ponceau 4R",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E210",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Ponceau SX",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E211",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Ponceau 6R",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E212",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Erythrosine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E213",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Red 2G",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E214",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Allura Red AC",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E215",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Indanthrene Blue RS",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E216",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Patent Blue V",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E217",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Indigo Carmine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E218",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Brilliant Blue FCF",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E219",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Chlorophylls and Chlorophyllins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E220",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Copper Complexes of Chlorophylls and Chlorophyllins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E221",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Green S",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E222",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Fast Green FCF",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E223",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Plain Caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E224",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Caustic Sulfite Caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E225",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Ammonia Caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E226",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sulfite Ammonia Caramel",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E227",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Black PN",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E228",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Carbon Black",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E230",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Brown FK",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E231",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Brown HT",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E232",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Alpha-carotene, Beta-carotene, Gamma-carotene",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E233",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Annatto, bixin, norbixin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E234",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Paprika oleoresin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E235",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Lycopene",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E236",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Beta-apo-8'-carotenal",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E237",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Ethyl ester of beta-apo-8'-carotenic acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E238",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Flavoxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E239",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Lutein",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E240",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Cryptoxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E242",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Rubixanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E249",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Violaxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E250",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Rhodoxanthin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E251",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Beetroot Red",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E260",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Anthocyanins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E261",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium Carbonate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E262",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Titanium Dioxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E263",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Iron Oxides and Iron Hydroxides",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E264",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Aluminium",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E280",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Silver",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E281",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Gold",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E282",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Pigment Rubine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E283",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Tannin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E284",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sorbic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E285",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Sodium Sorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E290",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Potassium Sorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E296",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Calcium Sorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E297",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Benzoic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E300",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ascorbic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E301",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Benzoate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E302",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Benzoate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E303",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ethylparaben",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E304",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Ethyl para-hydroxybenzoate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E306",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Propylparaben",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E307",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Propyl para-hydroxybenzoate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E307b",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Conc. mixed tocopherols (beta, gamma)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E308",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Methylparaben",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E309",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Methyl para-hydroxybenzoate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E310",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sulfur Dioxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E311",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Sulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E312",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Bisulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E315",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Metabisulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E316",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Metabisulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E317",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Sulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E318",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Sulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E319",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Hydrogen Sulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E320",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Hydrogen Sulfite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E321",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Biphenyl",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E329",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Orthophenyl Phenol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E330",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Orthophenyl Phenol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E331",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Thiabendazole",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E332",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Nisin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E333",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Natamycin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E334",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Formic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E335",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Formate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E336",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Formate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E337",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Hexamine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E338",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Formaldehyde",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E339",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Dimethyl Dicarbonate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E340",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Nitrite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E341",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Nitrite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E343",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Nitrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E350",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Acetic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E351",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Acetate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E352",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Acetates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E353",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Acetate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E354",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ammonium Acetate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E355",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Propionic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E356",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Propionate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E357",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Propionate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E363",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Potassium Propionate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E365",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Boric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E366",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Tetraborate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E367",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Carbon Dioxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E370",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Malic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E375",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Fumaric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E380",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Ascorbic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E381",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Sodium Ascorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E385",
    type: ENumberArrayType.ANTIOXIDANT,
    name: "Calcium Ascorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E400",
    type: ENumberArrayType.EMULSIFIER,
    name: "Potassium Ascorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E401",
    type: ENumberArrayType.EMULSIFIER,
    name: "Fatty Acid Esters of Ascorbic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E402",
    type: ENumberArrayType.EMULSIFIER,
    name: "Tocopherols",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E403",
    type: ENumberArrayType.EMULSIFIER,
    name: "Alpha-Tocopherol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E404",
    type: ENumberArrayType.EMULSIFIER,
    name: "Gamma-Tocopherol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E405",
    type: ENumberArrayType.EMULSIFIER,
    name: "Delta-Tocopherol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E406",
    type: ENumberArrayType.EMULSIFIER,
    name: "Propyl Gallate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E407",
    type: ENumberArrayType.EMULSIFIER,
    name: "Octyl Gallate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E407a",
    type: ENumberArrayType.EMULSIFIER,
    name: "Processed eucheuma seaweed",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E410",
    type: ENumberArrayType.EMULSIFIER,
    name: "Dodecyl Gallate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E412",
    type: ENumberArrayType.EMULSIFIER,
    name: "Erythorbic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E413",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sodium Erythorbate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E414",
    type: ENumberArrayType.EMULSIFIER,
    name: "Erythorbin Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E415",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sodium Erythorbin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E416",
    type: ENumberArrayType.EMULSIFIER,
    name: "tert-Butylhydroquinone",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E417",
    type: ENumberArrayType.EMULSIFIER,
    name: "Butylated Hydroxyanisole",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E418",
    type: ENumberArrayType.EMULSIFIER,
    name: "Butylated Hydroxytoluene",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E420",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sorbitol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E421",
    type: ENumberArrayType.EMULSIFIER,
    name: "Mannitol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E425",
    type: ENumberArrayType.EMULSIFIER,
    name: "Magnesium Lactate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E440",
    type: ENumberArrayType.EMULSIFIER,
    name: "Pectins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E444",
    type: ENumberArrayType.EMULSIFIER,
    name: "Sucrose acetate isobutyrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E445",
    type: ENumberArrayType.EMULSIFIER,
    name: "Glycerol esters of wood rosin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E450",
    type: ENumberArrayType.EMULSIFIER,
    name: "Diphosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E451",
    type: ENumberArrayType.EMULSIFIER,
    name: "Triphosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E452",
    type: ENumberArrayType.EMULSIFIER,
    name: "Polyphosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E459",
    type: ENumberArrayType.EMULSIFIER,
    name: "Beta-cyclodextrin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E460",
    type: ENumberArrayType.EMULSIFIER,
    name: "Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E461",
    type: ENumberArrayType.EMULSIFIER,
    name: "Methyl cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E462",
    type: ENumberArrayType.EMULSIFIER,
    name: "Ethyl cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E463",
    type: ENumberArrayType.EMULSIFIER,
    name: "Hydroxypropyl cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E464",
    type: ENumberArrayType.EMULSIFIER,
    name: "Hydroxypropyl methylcellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E465",
    type: ENumberArrayType.EMULSIFIER,
    name: "Ethyl methylcellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E466",
    type: ENumberArrayType.EMULSIFIER,
    name: "Carboxymethyl cellulose (CMC)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E468",
    type: ENumberArrayType.EMULSIFIER,
    name: "Crosslinked CMC (CMC-Na)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E469",
    type: ENumberArrayType.EMULSIFIER,
    name: "Enzymatically hydrolysed CMC",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E500",
    type: ENumberArrayType.OTHER,
    name: "Sodium carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E501",
    type: ENumberArrayType.OTHER,
    name: "Potassium carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E503",
    type: ENumberArrayType.OTHER,
    name: "Ammonium carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E504",
    type: ENumberArrayType.OTHER,
    name: "Magnesium carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E507",
    type: ENumberArrayType.OTHER,
    name: "Hydrochloric acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E508",
    type: ENumberArrayType.OTHER,
    name: "Potassium chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E509",
    type: ENumberArrayType.OTHER,
    name: "Calcium chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E510",
    type: ENumberArrayType.OTHER,
    name: "Ammonium chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E511",
    type: ENumberArrayType.OTHER,
    name: "Magnesium chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E512",
    type: ENumberArrayType.OTHER,
    name: "Stannous chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E513",
    type: ENumberArrayType.OTHER,
    name: "Sulfuric acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E517",
    type: ENumberArrayType.OTHER,
    name: "Ammonium sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E518",
    type: ENumberArrayType.OTHER,
    name: "Magnesium sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E519",
    type: ENumberArrayType.OTHER,
    name: "Copper sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E520",
    type: ENumberArrayType.OTHER,
    name: "Aluminium sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E521",
    type: ENumberArrayType.OTHER,
    name: "Aluminium sodium sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E522",
    type: ENumberArrayType.OTHER,
    name: "Aluminium potassium sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E523",
    type: ENumberArrayType.OTHER,
    name: "Aluminium ammonium sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E524",
    type: ENumberArrayType.OTHER,
    name: "Sodium hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E525",
    type: ENumberArrayType.OTHER,
    name: "Potassium hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E526",
    type: ENumberArrayType.OTHER,
    name: "Calcium hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E527",
    type: ENumberArrayType.OTHER,
    name: "Ammonium hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E528",
    type: ENumberArrayType.OTHER,
    name: "Magnesium hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E529",
    type: ENumberArrayType.OTHER,
    name: "Calcium oxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E530",
    type: ENumberArrayType.OTHER,
    name: "Magnesium oxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E535",
    type: ENumberArrayType.OTHER,
    name: "Sodium ferrocyanide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E536",
    type: ENumberArrayType.OTHER,
    name: "Potassium ferrocyanide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E538",
    type: ENumberArrayType.OTHER,
    name: "Calcium ferrocyanide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E540",
    type: ENumberArrayType.OTHER,
    name: "Dicalcium diphosphite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E541",
    type: ENumberArrayType.OTHER,
    name: "Sodium aluminium phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E543",
    type: ENumberArrayType.OTHER,
    name: "Calcium aluminium phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E544",
    type: ENumberArrayType.OTHER,
    name: "Magnesium aluminium silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E545",
    type: ENumberArrayType.OTHER,
    name: "Ammonium aluminium silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E550",
    type: ENumberArrayType.OTHER,
    name: "Sodium silicates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E551",
    type: ENumberArrayType.OTHER,
    name: "Silicon dioxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E552",
    type: ENumberArrayType.OTHER,
    name: "Calcium silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E553b",
    type: ENumberArrayType.OTHER,
    name: "Talc",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E554",
    type: ENumberArrayType.OTHER,
    name: "Sodium aluminosilicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E555",
    type: ENumberArrayType.OTHER,
    name: "Potassium aluminium silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E556",
    type: ENumberArrayType.OTHER,
    name: "Calcium aluminium silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E558",
    type: ENumberArrayType.OTHER,
    name: "Bentonite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E559",
    type: ENumberArrayType.OTHER,
    name: "Aluminium silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E574",
    type: ENumberArrayType.OTHER,
    name: "Gluconic acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E575",
    type: ENumberArrayType.OTHER,
    name: "Glucono delta-lactone",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E576",
    type: ENumberArrayType.OTHER,
    name: "Sodium gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E577",
    type: ENumberArrayType.OTHER,
    name: "Potassium gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E578",
    type: ENumberArrayType.OTHER,
    name: "Calcium gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E579",
    type: ENumberArrayType.OTHER,
    name: "Iron(II) gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E620",
    type: ENumberArrayType.OTHER,
    name: "Glutamic acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E621",
    type: ENumberArrayType.OTHER,
    name: "Monosodium glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E622",
    type: ENumberArrayType.OTHER,
    name: "Monopotassium glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E623",
    type: ENumberArrayType.OTHER,
    name: "Monoammonium glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E624",
    type: ENumberArrayType.OTHER,
    name: "Monocalcium glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E625",
    type: ENumberArrayType.OTHER,
    name: "Magnesium diglutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E626",
    type: ENumberArrayType.OTHER,
    name: "Guanylic acid (5'-GMP)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E628",
    type: ENumberArrayType.OTHER,
    name: "Disodium guanylate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E629",
    type: ENumberArrayType.OTHER,
    name: "Dipotassium guanylate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E630",
    type: ENumberArrayType.OTHER,
    name: "Inosinic acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E632",
    type: ENumberArrayType.OTHER,
    name: "Disodium inosinate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E633",
    type: ENumberArrayType.OTHER,
    name: "Dipotassium inosinate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E634",
    type: ENumberArrayType.OTHER,
    name: "Calcium 5'-ribonucleotides",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E636",
    type: ENumberArrayType.OTHER,
    name: "Maltol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E637",
    type: ENumberArrayType.OTHER,
    name: "Ethyl maltol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E900",
    type: ENumberArrayType.OTHER,
    name: "Dimethylpolysiloxane (antifoam)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E902",
    type: ENumberArrayType.OTHER,
    name: "Candelilla wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E903",
    type: ENumberArrayType.OTHER,
    name: "Carnauba wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E905",
    type: ENumberArrayType.OTHER,
    name: "Microcrystalline wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E905a",
    type: ENumberArrayType.OTHER,
    name: "Mineral oil (white oils)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E905b",
    type: ENumberArrayType.OTHER,
    name: "Petrolatum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E905c",
    type: ENumberArrayType.OTHER,
    name: "Paraffin wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E907",
    type: ENumberArrayType.OTHER,
    name: "Refined microcrystalline wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E908",
    type: ENumberArrayType.OTHER,
    name: "Rice bran wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E912",
    type: ENumberArrayType.OTHER,
    name: "Montan acid esters",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E914",
    type: ENumberArrayType.OTHER,
    name: "Oxidised polyethylene wax",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E915",
    type: ENumberArrayType.OTHER,
    name: "Glycerol ester of rosin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E922",
    type: ENumberArrayType.OTHER,
    name: "Potassium persulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E923",
    type: ENumberArrayType.OTHER,
    name: "Ammonium persulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E924",
    type: ENumberArrayType.OTHER,
    name: "Potassium bromate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E925",
    type: ENumberArrayType.OTHER,
    name: "Chlorine",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E926",
    type: ENumberArrayType.OTHER,
    name: "Chlorine dioxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E927",
    type: ENumberArrayType.OTHER,
    name: "Azodicarbonamide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E297b",
    type: ENumberArrayType.PRESERVATIVE,
    name: "Citric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E928",
    type: ENumberArrayType.OTHER,
    name: "Benzoyl peroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E930",
    type: ENumberArrayType.OTHER,
    name: "Calcium peroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E938",
    type: ENumberArrayType.OTHER,
    name: "Argon",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E939",
    type: ENumberArrayType.OTHER,
    name: "Helium",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E940",
    type: ENumberArrayType.OTHER,
    name: "Dichlorodifluoromethane (CFC-12)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E941",
    type: ENumberArrayType.OTHER,
    name: "Nitrogen",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E942",
    type: ENumberArrayType.OTHER,
    name: "Nitrous oxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E943a",
    type: ENumberArrayType.OTHER,
    name: "Butane",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E943b",
    type: ENumberArrayType.OTHER,
    name: "Isobutane",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E944",
    type: ENumberArrayType.OTHER,
    name: "Propane",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E948",
    type: ENumberArrayType.OTHER,
    name: "Oxygen",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E949",
    type: ENumberArrayType.OTHER,
    name: "Hydrogen",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E950",
    type: ENumberArrayType.SWEETENER,
    name: "Acesulfame K",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E951",
    type: ENumberArrayType.SWEETENER,
    name: "Aspartame",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E952",
    type: ENumberArrayType.SWEETENER,
    name: "Cyclamates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E953",
    type: ENumberArrayType.SWEETENER,
    name: "Isomalt",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E954",
    type: ENumberArrayType.SWEETENER,
    name: "Saccharin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E955",
    type: ENumberArrayType.SWEETENER,
    name: "Sucralose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E957",
    type: ENumberArrayType.SWEETENER,
    name: "Thaumatin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E959",
    type: ENumberArrayType.SWEETENER,
    name: "Neohesperidin dihydrochalcone",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E965",
    type: ENumberArrayType.SWEETENER,
    name: "Maltitol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E967",
    type: ENumberArrayType.SWEETENER,
    name: "Xylitol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E999",
    type: ENumberArrayType.OTHER,
    name: "Quillaia extracts (foaming agent)",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1103",
    type: ENumberArrayType.OTHER,
    name: "Sodium Citrates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1106",
    type: ENumberArrayType.OTHER,
    name: "Potassium Citrates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1107",
    type: ENumberArrayType.OTHER,
    name: "Calcium Citrates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1108",
    type: ENumberArrayType.OTHER,
    name: "Tartaric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1109",
    type: ENumberArrayType.OTHER,
    name: "Sodium Tartrates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1110",
    type: ENumberArrayType.OTHER,
    name: "Potassium Tartrates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1111",
    type: ENumberArrayType.OTHER,
    name: "Sodium Potassium Tartrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1112",
    type: ENumberArrayType.OTHER,
    name: "Phosphoric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1113",
    type: ENumberArrayType.OTHER,
    name: "Sodium Phosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1114",
    type: ENumberArrayType.OTHER,
    name: "Potassium Phosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1115",
    type: ENumberArrayType.OTHER,
    name: "Calcium Phosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1116",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Phosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1117",
    type: ENumberArrayType.OTHER,
    name: "Sodium Malates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1118",
    type: ENumberArrayType.OTHER,
    name: "Potassium Malate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1119",
    type: ENumberArrayType.OTHER,
    name: "Calcium Malates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1120",
    type: ENumberArrayType.OTHER,
    name: "Metatartaric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1121",
    type: ENumberArrayType.OTHER,
    name: "Calcium Tartrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1122",
    type: ENumberArrayType.OTHER,
    name: "Adipic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1123",
    type: ENumberArrayType.OTHER,
    name: "Sodium Adipate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1124",
    type: ENumberArrayType.OTHER,
    name: "Potassium Adipate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1125",
    type: ENumberArrayType.OTHER,
    name: "Succinic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1126",
    type: ENumberArrayType.OTHER,
    name: "Monosodium Fumarate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1127",
    type: ENumberArrayType.OTHER,
    name: "Potassium Fumarate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1128",
    type: ENumberArrayType.OTHER,
    name: "Calcium Fumarate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1129",
    type: ENumberArrayType.OTHER,
    name: "1,4-Heptonolactone",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1130",
    type: ENumberArrayType.OTHER,
    name: "Niacin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1131",
    type: ENumberArrayType.OTHER,
    name: "Triammonium Citrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1132",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Ferric Citrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1133",
    type: ENumberArrayType.OTHER,
    name: "Calcium Disodium EDTA",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1134",
    type: ENumberArrayType.OTHER,
    name: "Alginic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1135",
    type: ENumberArrayType.OTHER,
    name: "Sodium Alginate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1136",
    type: ENumberArrayType.OTHER,
    name: "Potassium Alginate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1137",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Alginate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1138",
    type: ENumberArrayType.OTHER,
    name: "Calcium Alginate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1139",
    type: ENumberArrayType.OTHER,
    name: "Propane-1,2-diol Alginate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1140",
    type: ENumberArrayType.OTHER,
    name: "Agar",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1141",
    type: ENumberArrayType.OTHER,
    name: "Carrageenan",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1142",
    type: ENumberArrayType.OTHER,
    name: "Processed Eucheuma Seaweed",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1143",
    type: ENumberArrayType.OTHER,
    name: "Locust Bean Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1144",
    type: ENumberArrayType.OTHER,
    name: "Guar Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1145",
    type: ENumberArrayType.OTHER,
    name: "Tragacanth",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1146",
    type: ENumberArrayType.OTHER,
    name: "Acacia Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1147",
    type: ENumberArrayType.OTHER,
    name: "Xanthan Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1148",
    type: ENumberArrayType.OTHER,
    name: "Karaya Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1149",
    type: ENumberArrayType.OTHER,
    name: "Tara Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1150",
    type: ENumberArrayType.OTHER,
    name: "Gellan Gum",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1151",
    type: ENumberArrayType.OTHER,
    name: "Sorbitol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1152",
    type: ENumberArrayType.OTHER,
    name: "Mannitol",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1153",
    type: ENumberArrayType.OTHER,
    name: "Konjac",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1154",
    type: ENumberArrayType.OTHER,
    name: "Pectins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1155",
    type: ENumberArrayType.OTHER,
    name: "Sucrose Acetate Isobutyrate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1156",
    type: ENumberArrayType.OTHER,
    name: "Glycerol Esters of Wood Rosins",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1157",
    type: ENumberArrayType.OTHER,
    name: "Diphosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1158",
    type: ENumberArrayType.OTHER,
    name: "Triphosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1159",
    type: ENumberArrayType.OTHER,
    name: "Polyphosphates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1160",
    type: ENumberArrayType.OTHER,
    name: "Beta-cyclodextrin",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1161",
    type: ENumberArrayType.OTHER,
    name: "Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1162",
    type: ENumberArrayType.OTHER,
    name: "Methyl Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1163",
    type: ENumberArrayType.OTHER,
    name: "Ethyl Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1164",
    type: ENumberArrayType.OTHER,
    name: "Hydroxypropyl Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1165",
    type: ENumberArrayType.OTHER,
    name: "Hypromellose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1166",
    type: ENumberArrayType.OTHER,
    name: "Ethyl Methyl Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1167",
    type: ENumberArrayType.OTHER,
    name: "Carboxymethyl Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1168",
    type: ENumberArrayType.OTHER,
    name: "Crosslinked Sodium Carboxymethyl Cellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1169",
    type: ENumberArrayType.OTHER,
    name: "Enzymically Hydrolysed Carboxymethylcellulose",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1170",
    type: ENumberArrayType.OTHER,
    name: "Sodium Carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1171",
    type: ENumberArrayType.OTHER,
    name: "Potassium Carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1172",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1173",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Carbonates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1174",
    type: ENumberArrayType.OTHER,
    name: "Hydrochloric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1175",
    type: ENumberArrayType.OTHER,
    name: "Potassium Chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1176",
    type: ENumberArrayType.OTHER,
    name: "Calcium Chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1177",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1178",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1179",
    type: ENumberArrayType.OTHER,
    name: "Stannous Chloride",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1180",
    type: ENumberArrayType.OTHER,
    name: "Sulfuric Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1181",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1182",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1183",
    type: ENumberArrayType.OTHER,
    name: "Copper(II) Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1184",
    type: ENumberArrayType.OTHER,
    name: "Aluminium Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1185",
    type: ENumberArrayType.OTHER,
    name: "Aluminium Sodium Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1186",
    type: ENumberArrayType.OTHER,
    name: "Aluminium Potassium Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1187",
    type: ENumberArrayType.OTHER,
    name: "Aluminium Ammonium Sulfate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1188",
    type: ENumberArrayType.OTHER,
    name: "Sodium Hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1189",
    type: ENumberArrayType.OTHER,
    name: "Potassium Hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1190",
    type: ENumberArrayType.OTHER,
    name: "Calcium Hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1191",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1192",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Hydroxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1193",
    type: ENumberArrayType.OTHER,
    name: "Calcium Oxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1194",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Oxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1195",
    type: ENumberArrayType.OTHER,
    name: "Sodium Ferrocyanide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1196",
    type: ENumberArrayType.OTHER,
    name: "Potassium Ferrocyanide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1197",
    type: ENumberArrayType.OTHER,
    name: "Calcium Ferrocyanide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1198",
    type: ENumberArrayType.OTHER,
    name: "Dicalcium Diphosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1199",
    type: ENumberArrayType.OTHER,
    name: "Sodium Aluminium Phosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1200",
    type: ENumberArrayType.OTHER,
    name: "Calcium Sodium Polyphosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1201",
    type: ENumberArrayType.OTHER,
    name: "Calcium Polyphosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1202",
    type: ENumberArrayType.OTHER,
    name: "Ammonium Polyphosphate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1400",
    type: ENumberArrayType.OTHER,
    name: "Sodium Silicates",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1401",
    type: ENumberArrayType.OTHER,
    name: "Silicon Dioxide",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1402",
    type: ENumberArrayType.OTHER,
    name: "Calcium Silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1403",
    type: ENumberArrayType.OTHER,
    name: "Talc",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1404",
    type: ENumberArrayType.OTHER,
    name: "Sodium Aluminosilicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1410",
    type: ENumberArrayType.OTHER,
    name: "Potassium Aluminium Silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1412",
    type: ENumberArrayType.OTHER,
    name: "Calcium Aluminosilicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1413",
    type: ENumberArrayType.OTHER,
    name: "Bentonite",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1414",
    type: ENumberArrayType.OTHER,
    name: "Aluminium Silicate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1420",
    type: ENumberArrayType.OTHER,
    name: "Gluconic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1421",
    type: ENumberArrayType.OTHER,
    name: "Glucono Delta-lactone",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1422",
    type: ENumberArrayType.OTHER,
    name: "Sodium Gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1430",
    type: ENumberArrayType.OTHER,
    name: "Potassium Gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1440",
    type: ENumberArrayType.OTHER,
    name: "Calcium Gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1441",
    type: ENumberArrayType.OTHER,
    name: "Ferrous Gluconate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1442",
    type: ENumberArrayType.OTHER,
    name: "Glutamic Acid",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1450",
    type: ENumberArrayType.OTHER,
    name: "Monosodium Glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1451",
    type: ENumberArrayType.OTHER,
    name: "Monopotassium Glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1505",
    type: ENumberArrayType.OTHER,
    name: "Calcium Diglutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1510",
    type: ENumberArrayType.OTHER,
    name: "Monoammonium Glutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1518",
    type: ENumberArrayType.OTHER,
    name: "Magnesium Diglutamate",
    licensedInEU: true,
    vegan: true,
  },
  {
    code: "E1520",
    type: ENumberArrayType.OTHER,
    name: "Guanylic Acid",
    licensedInEU: true,
    vegan: true,
  },
];
